-- init.lua
-- Neovim Configuration

require("general")
require("globals")
require("autoreplace")
require("search")
require("appearance")
require("mappings")
require("plugins")
require("filetree")
require("lsp")
require("debugging")
require("colorscheme")
require("statusline")
require("rooter")
require("prettier")
require("terminal")
require("snippets")
require("testrunner")
require("boundaries")
require("completion")
require("tabline")
